# Numpy

Documentation: https://docs.scipy.org/doc/numpy/reference/routines.html

Official Website: http://www.numpy.org/

Intro to Numpy: [Youtube Video](https://www.youtube.com/embed/rN0TREj8G7U)

## Import NumPy package

In [1]:
import os

In [2]:
import numpy as np

## Arrays

In [3]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [4]:
# data type

a.dtype

dtype('int64')

In [5]:
b = np.array([2.5,3.1,4.3])
b

array([2.5, 3.1, 4.3])

In [6]:
# data type

b.dtype

dtype('float64')

In [7]:
c = np.array([(1, 2, 3.5), (4, 5.2, 6)])
c

array([[1. , 2. , 3.5],
       [4. , 5.2, 6. ]])

In [8]:
# create an array with zeros

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# create an array with ones

np.ones((2,3,4), dtype=np.int16)    

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [10]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [11]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(4)

array([0, 1, 2, 3])

In [13]:
np.linspace(0, 2, 9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## Basic operations

In [14]:
a = np.arange(5)
b = np.linspace(1, 10, 5)

In [15]:
print(a)

[0 1 2 3 4]


In [16]:
print(b)

[ 1.    3.25  5.5   7.75 10.  ]


In [17]:
c = b - a
print(c)

[1.   2.25 3.5  4.75 6.  ]


In [18]:
# b to the power of two

d = b**2
print(d)

[  1.      10.5625  30.25    60.0625 100.    ]


In [19]:
e = 2 * np.sin(b)
print(e)

[ 1.68294197 -0.21639027 -1.41108065  1.98919756 -1.08804222]


In [20]:
# boolean data type

f = b<4
print(f)

[ True  True False False False]


In [21]:
# find the minimum of the array

print(e.min())

-1.4110806511407838


In [22]:
# find the maximum of the array

print(e.max())

1.9891975582223522


In [23]:
# sum all of the entries of the array

print(e.sum())

0.9566263858584052


In [24]:
# calculate the mean of the array

print(e.mean())

0.19132527717168105


## Indexing, Slicing, Iterating

In [25]:
a = np.array([(5,1,9,3), (8,1,26,3.4), (45,9.5,2,13)])
print(a)

[[ 5.   1.   9.   3. ]
 [ 8.   1.  26.   3.4]
 [45.   9.5  2.  13. ]]


In [26]:
# get a single entry from the array
a[2,2]

2.0

In [27]:
# get a row from the array
a[1, :]

array([ 8. ,  1. , 26. ,  3.4])

In [28]:
# get a column from the array

a[:, 1]

array([1. , 1. , 9.5])

In [29]:
for row in a:
    print(row)

[5. 1. 9. 3.]
[ 8.   1.  26.   3.4]
[45.   9.5  2.  13. ]


In [30]:
for entry in a[1, :]:
    print(entry)

8.0
1.0
26.0
3.4


## Shape

In [31]:
a.shape

(3, 4)

## Linear Algebra

https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [32]:
vector = np.arange(2, 20, 1.5)
vector

array([ 2. ,  3.5,  5. ,  6.5,  8. ,  9.5, 11. , 12.5, 14. , 15.5, 17. ,
       18.5])

In [33]:
matrix = vector.reshape(3, 4)
matrix

array([[ 2. ,  3.5,  5. ,  6.5],
       [ 8. ,  9.5, 11. , 12.5],
       [14. , 15.5, 17. , 18.5]])

In [34]:
# calculate the norm of the vector

np.linalg.norm(vector)

39.78064856183217

In [35]:
# calculate the norm of the matrix

np.linalg.norm(matrix, axis=0)

array([16.24807681, 18.51350858, 20.85665361, 23.25403191])

In [36]:
# solve a linear equation system m * x = n

m = np.array([[3,1], [1,2]])
n = np.array([9,8])
x = np.linalg.solve(m, n)
x

array([2., 3.])

## Random Sampling

https://docs.scipy.org/doc/numpy/reference/routines.random.html

In [37]:
# Return a sample (or samples) from the “standard normal” distribution

np.random.randn()

2.9692018668877234

In [38]:
np.random.randn(10)

array([ 0.93154702, -0.10861963, -0.03420436, -0.11038218,  0.35670292,
        1.80602193, -1.19016302,  1.1529501 ,  0.10511404, -0.08702843])

In [39]:
np.random.randn(3, 5)

array([[-0.45396313,  0.81765875, -0.6221693 , -1.15800727,  0.67992528],
       [ 0.78171253,  1.15103621, -0.29887602,  0.82616452, -0.41566656],
       [-1.07952585,  1.12868421, -1.5985507 , -1.33902435,  0.64205462]])

In [40]:
# Return random integers from low (inclusive) to high (exclusive)

np.random.randint(5)

1

In [41]:
np.random.randint(5, high=100)

25

In [42]:
np.random.randint(5, high=100, size=(5, 3))

array([[18, 31, 11],
       [94, 43, 48],
       [ 6, 77, 81],
       [93, 16, 29],
       [51, 19, 65]])

## Input and Output

https://docs.scipy.org/doc/numpy/reference/routines.io.html

In [43]:
if not os.path.isdir('data'):
    os.mkdir('data')
txt = np.random.randn(3, 5)
np.savetxt('data/test.txt', txt, delimiter=';')

In [44]:
# load data from a text file

data = np.loadtxt('data/test.txt', delimiter=';')
data

array([[ 0.54764446,  0.61319523,  1.75064837, -0.54904217,  0.01607031],
       [-0.70594116,  0.10015884,  0.64974772, -0.42589102, -1.18922067],
       [ 1.94717681, -0.75150697,  1.31972903, -2.13969986, -1.31157694]])

In [45]:
data = np.loadtxt('data/test.txt', delimiter=';', skiprows=1, usecols=(2, 3))
data

array([[ 0.64974772, -0.42589102],
       [ 1.31972903, -2.13969986]])