# Numpy

Documentation: https://docs.scipy.org/doc/numpy/reference/routines.html

Official Website: http://www.numpy.org/

Intro to Numpy: [Youtube Video](https://www.youtube.com/embed/rN0TREj8G7U)

## Import NumPy package

In [2]:
import os

In [3]:
import numpy as np

## Arrays

In [4]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [5]:
# data type

a.dtype

dtype('int32')

In [6]:
b = np.array([2.5,3.1,4.3])
b

array([2.5, 3.1, 4.3])

In [7]:
# data type

b.dtype

dtype('float64')

In [8]:
c = np.array([(1, 2, 3.5), (4, 5.2, 6)])
c

array([[1. , 2. , 3.5],
       [4. , 5.2, 6. ]])

In [9]:
# create an array with zeros

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# create an array with ones

np.ones((2,3,4), dtype=np.int16)    

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [11]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [12]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(4)

array([0, 1, 2, 3])

In [14]:
np.linspace(0, 2, 9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## Basic operations

In [15]:
a = np.arange(5)
b = np.linspace(1, 10, 5)

In [16]:
print(a)

[0 1 2 3 4]


In [17]:
print(b)

[ 1.    3.25  5.5   7.75 10.  ]


In [18]:
c = b - a
print(c)

[1.   2.25 3.5  4.75 6.  ]


In [19]:
# b to the power of two

d = b**2
print(d)

[  1.      10.5625  30.25    60.0625 100.    ]


In [20]:
e = 2 * np.sin(b)
print(e)

[ 1.68294197 -0.21639027 -1.41108065  1.98919756 -1.08804222]


In [21]:
# boolean data type

f = b<4
print(f)

[ True  True False False False]


In [22]:
# find the minimum of the array

print(e.min())

-1.4110806511407838


In [23]:
# find the maximum of the array

print(e.max())

1.9891975582223522


In [24]:
# sum all of the entries of the array

print(e.sum())

0.9566263858584052


In [25]:
# calculate the mean of the array

print(e.mean())

0.19132527717168105


## Indexing, Slicing, Iterating

In [26]:
a = np.array([(5,1,9,3), (8,1,26,3.4), (45,9.5,2,13)])
print(a)

[[ 5.   1.   9.   3. ]
 [ 8.   1.  26.   3.4]
 [45.   9.5  2.  13. ]]


In [27]:
# get a single entry from the array
a[2,2]

2.0

In [28]:
# get a row from the array
a[1, :]

array([ 8. ,  1. , 26. ,  3.4])

In [29]:
# get a column from the array

a[:, 1]

array([1. , 1. , 9.5])

In [30]:
for row in a:
    print(row)

[5. 1. 9. 3.]
[ 8.   1.  26.   3.4]
[45.   9.5  2.  13. ]


In [31]:
for entry in a[1, :]:
    print(entry)

8.0
1.0
26.0
3.4


## Shape

In [32]:
a.shape

(3, 4)

## Linear Algebra

https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [33]:
vector = np.arange(2, 20, 1.5)
vector

array([ 2. ,  3.5,  5. ,  6.5,  8. ,  9.5, 11. , 12.5, 14. , 15.5, 17. ,
       18.5])

In [34]:
matrix = vector.reshape(3, 4)
matrix

array([[ 2. ,  3.5,  5. ,  6.5],
       [ 8. ,  9.5, 11. , 12.5],
       [14. , 15.5, 17. , 18.5]])

In [35]:
# calculate the norm of the vector

np.linalg.norm(vector)

39.78064856183217

In [36]:
# calculate the norm of the matrix

np.linalg.norm(matrix, axis=0)

array([16.24807681, 18.51350858, 20.85665361, 23.25403191])

In [37]:
# solve a linear equation system m * x = n

m = np.array([[3,1], [1,2]])
n = np.array([9,8])
x = np.linalg.solve(m, n)
x

array([2., 3.])

## Random Sampling

https://docs.scipy.org/doc/numpy/reference/routines.random.html

In [38]:
# Return a sample (or samples) from the “standard normal” distribution

np.random.randn()

-0.19067733619368135

In [39]:
np.random.randn(10)

array([ 1.96679205,  0.94853147,  0.05405762, -0.56305469,  0.37389188,
       -0.28653711,  1.70877873, -0.48902596,  0.3226502 , -0.06643909])

In [40]:
np.random.randn(3, 5)

array([[-0.1480707 ,  0.3325172 ,  0.5442775 ,  0.11438211,  1.39576671],
       [ 0.14904063,  0.07200384,  0.28961747,  0.59977702, -0.48213084],
       [ 1.15348802, -0.33448   , -0.47043306,  1.02296152,  0.09578183]])

In [41]:
# Return random integers from low (inclusive) to high (exclusive)

np.random.randint(5)

4

In [42]:
np.random.randint(5, high=100)

9

In [43]:
np.random.randint(5, high=100, size=(5, 3))

array([[15, 47, 94],
       [49, 91, 57],
       [91, 21, 24],
       [53, 62, 22],
       [25, 34, 22]])

## Input and Output

https://docs.scipy.org/doc/numpy/reference/routines.io.html

In [44]:
if not os.path.isdir('data'):
    os.mkdir('data')
txt = np.random.randn(3, 5)
np.savetxt('data/test.txt', txt, delimiter=';')

In [45]:
# load data from a text file

data = np.loadtxt('data/test.txt', delimiter=';')
data

array([[ 1.0070601 ,  0.61817958, -1.63733492, -0.91066212,  1.19111352],
       [ 1.0069796 , -0.31843271, -0.12643498,  0.49886393, -0.03337408],
       [ 1.14374851,  0.36936662, -2.3534471 , -0.81682581,  0.16249965]])

In [46]:
data = np.loadtxt('data/test.txt', delimiter=';', skiprows=1, usecols=(2, 3))
data

array([[-0.12643498,  0.49886393],
       [-2.3534471 , -0.81682581]])